export interface CountryCode {
  value: string;
  label: string;
  dialCode: string;
  flag: string;
}

export const COUNTRY_CODES: CountryCode[] = [
  { value: 'US', label: 'United States', dialCode: '+1', flag: '🇺🇸' },
  { value: 'GB', label: 'United Kingdom', dialCode: '+44', flag: '🇬🇧' },
  { value: 'CA', label: 'Canada', dialCode: '+1', flag: '🇨🇦' },
  { value: 'AU', label: 'Australia', dialCode: '+61', flag: '🇦🇺' },
  { value: 'DE', label: 'Germany', dialCode: '+49', flag: '🇩🇪' },
  { value: 'FR', label: 'France', dialCode: '+33', flag: '🇫🇷' },
  { value: 'ES', label: 'Spain', dialCode: '+34', flag: '🇪🇸' },
  { value: 'IT', label: 'Italy', dialCode: '+39', flag: '🇮🇹' },
  { value: 'NL', label: 'Netherlands', dialCode: '+31', flag: '🇳🇱' },
  { value: 'BE', label: 'Belgium', dialCode: '+32', flag: '🇧🇪' },
  { value: 'SE', label: 'Sweden', dialCode: '+46', flag: '🇸🇪' },
  { value: 'NO', label: 'Norway', dialCode: '+47', flag: '🇳🇴' },
  { value: 'DK', label: 'Denmark', dialCode: '+45', flag: '🇩🇰' },
  { value: 'FI', label: 'Finland', dialCode: '+358', flag: '🇫🇮' },
  { value: 'CH', label: 'Switzerland', dialCode: '+41', flag: '🇨🇭' },
  { value: 'AT', label: 'Austria', dialCode: '+43', flag: '🇦🇹' },
  { value: 'PT', label: 'Portugal', dialCode: '+351', flag: '🇵🇹' },
  { value: 'PL', label: 'Poland', dialCode: '+48', flag: '🇵🇱' },
  { value: 'CZ', label: 'Czech Republic', dialCode: '+420', flag: '🇨🇿' },
  { value: 'RU', label: 'Russia', dialCode: '+7', flag: '🇷🇺' },
  { value: 'TR', label: 'Turkey', dialCode: '+90', flag: '🇹🇷' },
  { value: 'SA', label: 'Saudi Arabia', dialCode: '+966', flag: '🇸🇦' },
  { value: 'AE', label: 'UAE', dialCode: '+971', flag: '🇦🇪' },
  { value: 'IL', label: 'Israel', dialCode: '+972', flag: '🇮🇱' },
  { value: 'IN', label: 'India', dialCode: '+91', flag: '🇮🇳' },
  { value: 'CN', label: 'China', dialCode: '+86', flag: '🇨🇳' },
  { value: 'JP', label: 'Japan', dialCode: '+81', flag: '🇯🇵' },
  { value: 'KR', label: 'South Korea', dialCode: '+82', flag: '🇰🇷' },
  { value: 'SG', label: 'Singapore', dialCode: '+65', flag: '🇸🇬' },
  { value: 'HK', label: 'Hong Kong', dialCode: '+852', flag: '🇭🇰' },
  { value: 'TW', label: 'Taiwan', dialCode: '+886', flag: '🇹🇼' },
  { value: 'TH', label: 'Thailand', dialCode: '+66', flag: '🇹🇭' },
  { value: 'MY', label: 'Malaysia', dialCode: '+60', flag: '🇲🇾' },
  { value: 'ID', label: 'Indonesia', dialCode: '+62', flag: '🇮🇩' },
  { value: 'PH', label: 'Philippines', dialCode: '+63', flag: '🇵🇭' },
  { value: 'VN', label: 'Vietnam', dialCode: '+84', flag: '🇻🇳' },
  { value: 'PK', label: 'Pakistan', dialCode: '+92', flag: '🇵🇰' },
  { value: 'BD', label: 'Bangladesh', dialCode: '+880', flag: '🇧🇩' },
  { value: 'NG', label: 'Nigeria', dialCode: '+234', flag: '🇳🇬' },
  { value: 'ZA', label: 'South Africa', dialCode: '+27', flag: '🇿🇦' },
  { value: 'EG', label: 'Egypt', dialCode: '+20', flag: '🇪🇬' },
  { value: 'KE', label: 'Kenya', dialCode: '+254', flag: '🇰🇪' },
  { value: 'GH', label: 'Ghana', dialCode: '+233', flag: '🇬🇭' },
  { value: 'BR', label: 'Brazil', dialCode: '+55', flag: '🇧🇷' },
  { value: 'MX', label: 'Mexico', dialCode: '+52', flag: '🇲🇽' },
  { value: 'AR', label: 'Argentina', dialCode: '+54', flag: '🇦🇷' },
  { value: 'CO', label: 'Colombia', dialCode: '+57', flag: '🇨🇴' },
  { value: 'CL', label: 'Chile', dialCode: '+56', flag: '🇨🇱' },
  { value: 'PE', label: 'Peru', dialCode: '+51', flag: '🇵🇪' },
  { value: 'NZ', label: 'New Zealand', dialCode: '+64', flag: '🇳🇿' },
];
