export const UNIT_OPTIONS = [
  { value: 'kilometer', label: 'Kilometer' },
  { value: 'meter', label: 'Meter' },
  { value: 'centimeter', label: 'Centimeter' },
  { value: 'millimeter', label: 'Millimeter' },
  { value: 'mile', label: 'Mile' },
  { value: 'yard', label: 'Yard' },
  { value: 'foot', label: 'Foot' },
  { value: 'inch', label: 'Inch' },
  { value: 'kilogram', label: 'Kilogram' },
  { value: 'gram', label: 'Gram' },
  { value: 'pound', label: 'Pound' },
  { value: 'ounce', label: 'Ounce' },
  { value: 'liter', label: 'Liter' },
  { value: 'milliliter', label: 'Milliliter' },
  { value: 'gallon', label: 'Gallon' },
  { value: 'celsius', label: 'Celsius' },
  { value: 'fahrenheit', label: 'Fahrenheit' },
  { value: 'kelvin', label: 'Kelvin' },
];